apiVersion: 1

deleteDatasources:
  - name: "Node Exporter Prometheus"
  - name: "Prometheus (Self & cAdvisor)"
  - name: "Redis Exporter Prometheus"

datasources:
  - name: "Prometheus"
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    database: sales_db
    user: postgres
    secureJsonData:
      password: admin
    editable: false
    jsonData:
      sslmode: disable
      defaultSchema: public
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
