# handlers/grafana_handler.py
# Handler for Grafana API operations

import requests
from typing import Dict, List, Any, Optional


class GrafanaHandler:
    """Handler for Grafana API operations"""
    
    def __init__(self, grafana_host: str, grafana_key: str):
        """
        Initialize Grafana handler
        
        Args:
            grafana_host: Grafana instance URL (e.g., http://localhost:3000)
            grafana_key: Grafana API key with dashboard permissions
        """
        self.grafana_key = grafana_key
        self.grafana_host = grafana_host
        self.headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.grafana_key}"
        }

    def apply_dashboard(self, dashboard_json: Dict[str, Any]) -> Dict[str, Any]:
        """
        Apply/deploy dashboard to Grafana via API
        
        Args:
            dashboard_json: Complete dashboard JSON specification
            
        Returns:
            Dict with deployment result including URL
        """
        url = f"{self.grafana_host}/api/dashboards/db"
        payload = {
            "dashboard": dashboard_json,
            "overwrite": True,
            "message": "Auto-generated by VizGenie"
        }

        try:
            response = requests.post(url, json=payload, headers=self.headers, timeout=30)
            if response.status_code == 200:
                result = response.json()
                # Construct full URL
                result['url'] = f"{self.grafana_host}{result.get('url', '')}"
                return result
            return {
                "error": f"API Error {response.status_code}", 
                "details": response.text
            }
        except requests.exceptions.Timeout:
            return {"error": "Request timeout - Grafana took too long to respond"}
        except requests.exceptions.ConnectionError:
            return {"error": "Connection error - Could not reach Grafana"}
        except Exception as e:
            return {"error": f"Unexpected error: {str(e)}"}
        

    def fetch_datasources(self) -> List[Dict[str, Any]]:
        """
        Fetch and process datasources from Grafana
        
        Returns:
            List of processed datasource dictionaries
        """
        url = f"{self.grafana_host}/api/datasources"
        
        try:
            response = requests.get(url, headers=self.headers, timeout=10)
            if response.status_code == 200:
                processed_ds = []
                for ds in response.json():
                    ds_type = ds.get('typeName', '').lower()
                    
                    if ds_type == 'prometheus':
                        processed_ds.append({
                            "uid": ds.get('uid', ''),
                            "name": "prometheus",
                            "type": "prometheus",
                            "url": ds.get('url', ''),
                            "database": ds.get('database', '')
                        })
                    elif ds_type == 'postgresql':
                        processed_ds.append({
                            "uid": ds.get('uid', ''),
                            "name": "postgresql",
                            "type": "postgres",
                            "url": ds.get('url', ''),
                            "database": ds.get('database', '')
                        })
                
                return processed_ds
            else:
                print(f"Failed to fetch datasources: {response.status_code}")
                return []
                
        except Exception as e:
            print(f"Error fetching datasources: {str(e)}")
            return []
    
    def test_connection(self) -> bool:
        """
        Test Grafana connection
        
        Returns:
            True if connection successful, False otherwise
        """
        try:
            response = requests.get(
                f"{self.grafana_host}/api/datasources",
                headers=self.headers,
                timeout=5
            )
            return response.status_code == 200
        except Exception:
            return False